platform :ios, '12.1'
use_frameworks!

target 'TICExampleApp' do
  pod 'ffmpeg-kit-ios-video', '~> 5.1'
end
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
 end
end
